### PR TITLE
:lipstick: (PostItem): Fix layout based on design

### LINKED ISSUE #3: PostItem
Create Post Item Basic Layout

### LINKED ISSUE #4: PostItemList
Read from mock database a Post Item List for listing PostItems

### LINKED ISSUE #59: PostCard Component

### PR DESCRIPTION
**Pull request by behagoras**
card

---------------------->>

image

### CODE REVIEW

File: components/InfoPost.js [hunk 1]
```diff
@@ -3,22 +3,33 @@ import { parse, format } from 'date-fns'
...
-const Avatar = styled.img`
-  width:100%;
-  object-fit:cover;
-  border-radius:50%;
-  border:3px solid ${(props) => props.theme.color.primary};
-  box-sizing: border-box;
-`
+import useWidth from '../hooks/useWidth'
+
+// const Avatar = styled.img`
```
Comment (WilliamVelazquez) [inline components/InfoPost.js:10]: You should remove the comments before the Pull Request when you replace it by a Component and You will not use them anymore.

File: components/PostItemList.js [hunk 2]
```diff
@@ -15,7 +15,7 @@ const Container = styled.div`
 const Main = styled.div`
   display:grid;
   grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
-  grid-gap:${(props) => props.theme.space * 2}px;
+  grid-gap:${(props) => props.theme.space * 6}px ${(props) => props.theme.space * 1}px;
```
Comment (WilliamVelazquez) [inline components/PostItemList.js:18]: Is it necessary the 1 multiplier?

**Review by WilliamVelazquez — APPROVED** [review]
It looks ok but I made some notes.
